[tool.poetry]
name = "flockwave-server"
version = "2.17.1"
description = "Skybrush server component"
authors = [
    "Tamas Nepusz <tamas@collmot.com>",
    "Gabor Vasarhelyi <vasarhelyi@collmot.com>",
]
license = "GPL-3.0-or-later"
packages = [{ include = "flockwave", from = "src" }]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "collmot"
url = "https://pypi.collmot.com/simple/"
priority = "explicit"

[[tool.poetry.source]]
name = "fury"
url = "https://pypi.fury.io/skybrush/"
priority = "supplemental"

[tool.poetry.dependencies]
python = "^3.9"
bidict = ">=0.19.0"
click = "^8.0.0"
blinker = "^1.6"
jsonschema = "^4.19.2"
python-baseconv = "^1.2.2"
pynmea2 = "^1.15.0"
trio = ">=0.23.0"
quart = ">=0.19.3"
quart-trio = ">=0.11.0"
trio-util = ">=0.5.0"
python-dotenv = ">=0.14.0"
colour = ">=0.1.5"
pyjwt = "^2.8.0"
hypercorn = { extras = ["trio"], version = ">=0.10.1" }
passlib = { extras = ["bcrypt"], version = "^1.7.2" }
flockwave-app-framework = { version = "^2.6.0", extras = [
    "daemon",
], source = "fury" }
flockwave-async = { version = "^1.4.2", source = "fury" }
flockwave-conn = { extras = [
    "rpc",
    "serial",
], source = "fury", version = "^6.3.2" }
flockwave-ext = { version = "^1.24.3", source = "fury" }
flockwave-flockctrl = { version = "^2.17.0", source = "collmot", optional = true }
flockwave-gps = { version = "^3.0.0", source = "fury" }
flockwave-logger = { version = "^1.9.0", source = "fury" }
flockwave-mavlink = { version = ">=0.1.0", source = "fury" }
flockwave-net = { extras = ["async"], version = "^6.0.1", source = "fury" }
flockwave-parsers = { version = "^2.0.1", source = "fury" }
flockwave-spec = { version = "^1.80.0", source = "fury" }
skybrush-ext-dock = { version = "^1.0.0", source = "collmot", optional = true }
skybrush-ext-flight-report = { version = "^1.0.3", source = "collmot", optional = true }
skybrush-ext-flockctrl = { version = "^2.30.1", source = "collmot", optional = true }
skybrush-ext-map-cache = { version = "^1.1.0", source = "collmot", optional = true }
skybrush-ext-sidekick = { version = "^1.0.1", source = "collmot", optional = true }
skybrush-ext-timecode = { version = "^1.1.0", source = "collmot", optional = true }
skybrush-lib-mission-planning = { version = "^1.0.0", source = "collmot", optional = true }
pyledctrl = { version = "^4.0.1", source = "fury" }
aiocflib = "^3.0.0"
appdirs = "^1.4.4"
crcmod-plus = "^2.0"
msgpack = "^1.0.0"
aio-usb-hotplug = "^6.0.0"
pyserial = "^3.4"
compose = "^1.1.1"
adrenaline = "^2.0.0"
httpx = ">=0.18.2"
igrf-model = "^1.1.1"
deprecated = "^1.2.14"

[tool.poetry.group.dev.dependencies]
coverage = { extras = ["toml"], version = "^7.1.0" }
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-trio = ">=0.6.0"
pdoc = "^14.1.0"

[tool.poetry.extras]
all = [
    "flockwave-flockctrl",
    "skybrush-ext-dock",
    "skybrush-ext-flight-report",
    "skybrush-ext-flockctrl",
    "skybrush-ext-map-cache",
    "skybrush-ext-sidekick",
    "skybrush-ext-timecode",
    "skybrush-lib-mission-planning",
]
collmot = [
    "flockwave-flockctrl",
    "skybrush-ext-dock",
    "skybrush-ext-flight-report",
    "skybrush-ext-flockctrl",
    "skybrush-ext-map-cache",
    "skybrush-ext-timecode",
    "skybrush-lib-mission-planning",
]
pro = [
    "skybrush-ext-flight-report",
    "skybrush-ext-map-cache",
    "skybrush-ext-sidekick",
    "skybrush-ext-timecode",
    "skybrush-lib-mission-planning",
]

[tool.poetry.scripts]
skybrushd = "flockwave.server.launcher:start"
skybrush-gateway = "flockwave.gateway.launcher:start"
skybrush-proxy = "flockwave.proxy.launcher:start"

[tool.ruff]
ignore = ["B905", "C901", "E402", "E501"]
line-length = 80
select = ["B", "C", "E", "F", "W"]
extend-exclude = ["src/flockwave/server/ext/socketio/vendor"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
